#!/bin/bash

# Builds a local images according to params sent in
#

# Help
function usage {
    echo Usage:
    echo    build-docker [target]
    echo target:
    echo    \"jenkins-base\" - builds the base Jenkins image
    echo    \"build-box\" - builds a full build image
}
if [ -z "$1" ]; then
    usage
    exit
fi
if [[ "$1" == "jenkins-base" ]]; then
    docker build -t "avastmick/jenkins-base" ./jenkins/.
elif [[ "$1" == "build-box" ]]; then
    docker build -t "avastmick/build-box" .
else
    echo Unknown target!
    usage
    exit
fi
