#!/bin/bash

# Run up a Docker container to allow local host file editing, but execution in container etc.
# Image build with (from root of repo): docker build -y avastmick/jenkins-ansible-packer ./docker/.
docker run --name build-box -i -t -v $(pwd):/usr/local/repos avastmick/jenkins-ansible-packer /bin/bash
